---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    grafana.internal/instance: grafana
spec:
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "false"
    auth.generic_oauth:
      enabled: "true"
      name: Pocket-ID
      icon: signin
      scopes: openid profile email groups
      empty_scopes: "false"
      auth_url: https://id.phekno.io/authorize
      token_url: https://id.phekno.io/api/oidc/token
      api_url: https://id.phekno.io/api/oidc/userinfo
      login_attribute_path: preferred_username
      groups_attribute_path: groups
      name_attribute_path: name
      email_attribute_path: email
      use_pkce: "true"
      role_attribute_path: "contains(groups[*], 'admins') && 'Admin' || contains(groups[*], 'editors') && 'Editor' || 'Viewer'"
      allow_assign_grafana_admin: "true"
      allow_sign_up: "true"
      auto_login: "false"
    log:
      mode: console
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
      root_url: https://grafana.phekno.io
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          initContainers:
            - name: k8s-sidecar
              image: ghcr.io/kiwigrid/k8s-sidecar:2.5.0
              env:
                - name: FOLDER
                  value: /var/lib/grafana/dashboards
                - name: FOLDER_ANNOTATION
                  value: grafana_folder
                - name: LABEL
                  value: grafana_dashboard
                - name: IGNORE_ALREADY_PROCESSED
                  value: "true"
                - name: METHOD
                  value: WATCH
                - name: NAMESPACE
                  value: ALL
                - name: RESOURCE
                  value: configmap
                - name: REQ_METHOD
                  value: POST
                - name: REQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password-secret
                      key: GF_SECURITY_ADMIN_PASSWORD
                - name: REQ_URL
                  value: http://localhost:3000/api/admin/provisioning/dashboards/reload
                - name: REQ_USERNAME
                  value: admin
                - name: UNIQUE_FILENAMES
                  value: "true"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
              volumeMounts:
                - name: grafana-sidecar-dashboards
                  mountPath: /var/lib/grafana/dashboards
                - name: tmpfs
                  mountPath: /tmp
              restartPolicy: Always
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password-secret
                      key: GF_SECURITY_ADMIN_PASSWORD
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password-secret
                      key: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password-secret
                      key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
              volumeMounts:
                - name: grafana-sidecar-provider
                  mountPath: /etc/grafana/provisioning/dashboards/sidecar-provider.yaml
                  subPath: provider.yaml
                - name: grafana-sidecar-dashboards
                  mountPath: /var/lib/grafana/dashboards
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
            - name: grafana-sidecar-provider
              configMap:
                name: grafana-sidecar-provider
            - name: grafana-sidecar-dashboards
              emptyDir: {}
            - name: tmpfs
              emptyDir: {}
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn
  disableDefaultSecurityContext: All
