---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phekno-social
spec:
  secretName: phekno-social-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: phekno.social
  dnsNames:
    - phekno.social
    - "*.phekno.social"
