---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name romm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        DB_HOST: &dbHost "{{ .DB_HOST }}"
        DB_USER: &dbUser "{{ .DB_USER }}"
        DB_PASSWD: &dbPassword "{{ .DB_PASSWORD }}"
        DB_NAME: &dbName romm
        # db init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPassword
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        IGDB_CLIENT_ID: "{{ .IGDB_CLIENT_ID }}"
        IGDB_CLIENT_SECRET: "{{ .IGDB_CLIENT_SECRET }}"
        STEAMGRIDDB_API_KEY: "{{ .STEAMGRIDDB_API_KEY }}"
        RETROACHIEVEMENTS_API_KEY: "{{ .RETROACHIEVEMENTS_API_KEY }}"
        # DISABLE_USERPASS_LOGIN: "false"
        # OIDC_ENABLED: "false"
        # OIDC_PROVIDER: authentik
        # OIDC_CLIENT_ID: "{{ .ROMM_OIDC_CLIENT_ID }}"
        # OIDC_CLIENT_SECRET: "{{ .ROMM_OIDC_CLIENT_SECRET }}"
        # OIDC_REDIRECT_URI: https://romm.jory.dev/api/oauth/openid
        # OIDC_SERVER_APPLICATION_URL: https://sso.jory.dev/application/o/romm
        # ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: romm
    - extract:
        key: cloudnative-pg
