---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources: []
  # - ./mastodon/ks.yaml
  # - ./mastodon-fakerelay/ks.yaml
  # - ./mastodon-getmoarfediverse/ks.yaml
components:
  - ../../components/common
  - ../../components/repos/app-template
