---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-secret
    template:
      engineVersion: v2
      data:
        FORGEJO_DB_PASSWORD: "{{ .FORGEJO_DB_PASSWORD }}"
        FORGEJO_SECRET_KEY: "{{ .FORGEJO_SECRET_KEY }}"
        FORGEJO_INTERNAL_TOKEN: "{{ .FORGEJO_INTERNAL_TOKEN }}"
  dataFrom:
    - extract:
        key: forgejo
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-postgres
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-postgres-secret
    template:
      engineVersion: v2
      data:
        username: forgejo
        password: "{{ .FORGEJO_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: forgejo
