---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-auth
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ${APP}
  extAuth:
    http:
      backendRef:
        name: authelia
        namespace: security
        port: 9091
      path: /api/authz/ext-authz/
      headersToBackend:
        - cookie
        - authorization
        - x-forwarded-proto
        - x-forwarded-host
        - x-forwarded-uri
        - x-forwarded-for
