---
# yaml-language-server: $schema=https://schemas.zinn.ca/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mastodon-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
        OTP_SECRET: "{{ .OTP_SECRET }}"
        VAPID_PRIVATE_KEY: "{{ .VAPID_PRIVATE_KEY }}"
        VAPID_PUBLIC_KEY: "{{ .VAPID_PUBLIC_KEY }}"
        MASTODON_ADMIN_PASSWORD: "{{ .MASTODON_ADMIN_PASSWORD }}"
        SMTP_SERVER: "{{ .SMTP_HOST }}"
        SMTP_LOGIN: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: "{{ .ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY }}"
        ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: "{{ .ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT }}"
        ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: "{{ .ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY }}"
        DB_HOST: &dbhost postgres-rw.db.svc.cluster.local
        DB_NAME: &dbname mastodon
        DB_USER: &dbuser "{{ .DB_USERNAME }}"
        DB_PASS: &dbpass "{{ .DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: mastodon
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp
